IBM/python-sdk-core

ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/iam_token_manager.py
This PR is a follow-up to my previous IAM-related PR.
This PR contains additional changes to allow the SDK user to set the IAM client_id and client_secret values when instantiating a generated service class.   In this PR I've added the parameters to the BaseService ctor, which will be called by a generated service ctor.   Note that there will be a companion PR in the python generator to allow the new parameters to be set when instantiating the generated service class as well.
=> feat(IAM): allow IAM client id/secret to be set via BaseService ctor

ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/utils.py, test/test_base_service.py, test/test_utils.py
This PR supports the following:
* Convert data object to string before making a request
* Temporary handle vcap services... This is a temporary change as we pass in only `service name`. So a VCAP service like `compare-and-comply` would be converted to `compare_and_comply`
=> vcap and json loads changes

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
Now since the `x-alternate-name` is not present in the api definitions of major release, we can remove the `_from_dict ` step to avoid potential errors received especially in import/ export workspace
=> Model conversion

ibm_cloud_sdk_core/base_service.py
This PR adds error logs to various errors including ssl errors
=> feat(disable-ssl-verification): log error for ssl error and others

ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/jwt_token_manager.py, test/test_base_service.py
fixes: https://github.com/IBM/python-sdk-core/issues/31
=> fix(configs): Pass cllient configs to token managers

.travis.yml
This commit minimally modifies the .travis.yml file, but the main purpose of the commit
is to provide a commit that is friendly to semantic-release that will describe the
latest set of commits that were inadvertently merged into master without squashing
and whose commit messages do not follow the semantic-release conventions.
=> feat(BaseService): define new BaseService.configure_service function

.travis.yml
This PR serves two purposes:
1) Adds a commit with a properly-formatted commit message pertaining to the recent work to modify our VCAP_SERVICES function to support user-defined service names.
2) Adds python 3.8 to our list of versions that are used during Travis builds.   This list now includes 3.5, 3.6, 3.7 and 3.8.
=> feat: expand vcap credential loading to support user-defined service names

.releaserc
This PR fixes a minor issue related to semantic-release where the package-lock.json file might be updated as the result of running semantic-release, resulting in a "dirty workspace" and semrel refuses to proceed.
Adding `--allow-dirty` to bumpversion command.
=> chore: add --allow-dirty to bumpversion command

ibm_cloud_sdk_core/base_service.py
This PR makes a minor change to the logic for adding a user-agent header to the request if one is not already present.  The prior logic checked for user-agent in two different case forms, but the `headers` object is a `CaseInsensitiveDict`, so this logic is unnecessary.  A simple check for any case of `user-agent` is sufficient. To illustrate:
```
Last login: Fri Nov 15 12:54:55 on ttys009
[mkistler@mkistlers-MacBook-Pro] ~>python3
Python 3.7.3 (default, May 18 2019, 07:14:44) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> from requests.structures import CaseInsensitiveDict
>>> headers = {'user-agent': 'foo'}
>>> headers = CaseInsensitiveDict(headers)
>>> 'user-agent' in headers
True
>>> …
```
=> refactor: Simplify check for user-agent header in CaseInsensitiveDict

ibm_cloud_sdk_core/__init__.py, ibm_cloud_sdk_core/utils.py, test/test_utils.py
This PR adds utility methods to serialize and deserialize date values.
=> feat: Add date_to_string and string_to_date utility methods

ibm_cloud_sdk_core/utils.py, test/test_utils.py
This PR fixes the behavior of the recently added date/datetime_to_string methods to gracefully handle inputs that are not `date` or `datetime`.  Most importantly, these methods should return `None` if the input is `None`.  The new implementation simply returns the input argument whenever it is not of the expected type, which is consistent with the behavior of the other methods in the utils file.
=> fix: Fix date/datetime_to_string handling of non-date/datetime inputs

ibm_cloud_sdk_core/utils.py, test/test_utils.py
This PR fixes the `datetime_to_string` and `string_to_datetime` handling of dates without timezone information.
Python datetime values come in two forms: "naive" and "aware"
https://docs.python.org/3/library/datetime.html#aware-and-naive-objects
The fundamental difference between these two forms is that "naive" datetimes do not have a timezone, whereas "aware" datetimes do.
This PR fixes the core utility methods for converting datetime to/from strings.
=> Handle conversions for naive datetime values

ibm_cloud_sdk_core/api_exception.py, ibm_cloud_sdk_core/base_service.py
This PR fixes the override of the exception message for 401 error responses.  Previously the message was set unconditionally to a standard message in the SDK core.  Now that standard message is only used for 401 errors if no suitable error message is found in the response body.
Fixes #58.
=> Fix override of error message for 401 response

ibm_cloud_sdk_core/api_exception.py, ibm_cloud_sdk_core/authenticators/cp4d_authenticator.py, ibm_cloud_sdk_core/authenticators/iam_authenticator.py, ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/cp4d_token_manager.py, ibm_cloud_sdk_core/detailed_response.py, ibm_cloud_sdk_core/iam_token_manager.py, ibm_cloud_sdk_core/jwt_token_manager.py, ibm_cloud_sdk_core/utils.py, test/test_base_service.py, test/test_detailed_response.py, test/test_iam_token_manager.py, test/test_jwt_token_manager.py
Add a separator between positional and optional parameters and make optional parameters "keyword-only". This requires the user to specify the optional parameter they are setting instead of the relying on the position, since the arguments of an interface may change in the future.
https://python-3-for-scientists.readthedocs.io/en/latest/python3_advanced.html#keyword-only-arguments
=> Make optional parameters keyword-only

ibm_cloud_sdk_core/base_service.py
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1201
Currently the header `content-type` is unconditionally overridden to "application/json". This change will only add it if the header is not set.
=> [Breaking] Only override content-type if it is none

ibm_cloud_sdk_core/api_exception.py, ibm_cloud_sdk_core/authenticators/authenticator.py, ibm_cloud_sdk_core/authenticators/basic_authenticator.py, ibm_cloud_sdk_core/authenticators/bearer_token_authenticator.py, ibm_cloud_sdk_core/authenticators/cp4d_authenticator.py, ibm_cloud_sdk_core/authenticators/iam_authenticator.py, ibm_cloud_sdk_core/authenticators/no_auth_authenticator.py, ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/cp4d_token_manager.py, ibm_cloud_sdk_core/detailed_response.py, ibm_cloud_sdk_core/get_authenticator.py, ibm_cloud_sdk_core/iam_token_manager.py, ibm_cloud_sdk_core/jwt_token_manager.py, ibm_cloud_sdk_core/utils.py, test/test_base_service.py, test/test_detailed_response.py, test/test_iam_token_manager.py, test/test_jwt_token_manager.py, test/test_utils.py
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1598
Add Python 3.5 type annotations to parameters and return values.
I merged PR #61 into this branch so it includes those changes until I rebase when it is merged into `v2`.
=> Add type annotations to parameters and return values

ibm_cloud_sdk_core/utils.py, resources/ibm-credentials.env, test/test_utils.py
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1759
Changes:
- allow for a env config property's value to contain the ``=`` character
- add unit test cases
=> fix: allow '=' character in environment config values

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
Covered extra cases where trailing slash was not being removed when making a request.
=> fix: Strip trailing slash for request url

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
When service_url is none, rstrip will fail, this keeps the functionality before rstrip was added.
=> fix: Don't rstrip slash when service_url is none

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
Stripping the service url is incompatible with the current python unit tests. We will need to make a generator change along with the stripping change if we want to make them compatible.
=> fix: Revert service_url slash stripping to work with current tests

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1669
The fix added for stripping trailing slashes in both request URLs and service URLs causes an inconsistency in the python unit tests when checking the request and response URL.
Since changing the unit tests to to work with this core change would break compatibility for previous versions, this change is being moved to the v3.x version of the core where the new generator version with the unit test fix can specify the new core version.
=> fix: Revert stripping request URL trailing slashes

ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/jwt_token_manager.py, ibm_cloud_sdk_core/token_manager.py, test/test_jwt_token_manager.py, test/test_token_manager.py
Currently, JWTTokenManager is the top-most token manager class which
does not allow introducing new token managers in code that uses the IBM
Python SDK Core.
This commit refactors JWTTokenManager into an abstract
base class of TokenManager and the JWT-specific parts to allow extending
the Python SDK Core with non-JWT token managers.
This PR is analogous to https://github.com/IBM/node-sdk-core/pull/89
=> refactor: 💡 Refactor JWTTokenManager to introduce TokenManager

ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/utils.py, test/test_base_service.py
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1786
This fix combines the trailing slashes together to one. Since trailing slash and no trailing slash can mean different endpoints based on the server, we must repect which path is chosen.
Fixing the request URL like this will break compatibility with previous generator versions since their unit tests use the un-filtered url in the responses object.
=> fix: Combine multiple ending slashes to one

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
Fixes: arf/planning-sdk-squad/issues/901
This change allows generated operation code to pass 'stream=True' to
the BaseService.send() method, which will in turn pass it on to the
underlying requests.request() method.  The net result is that
the response body (even if it is a JSON object) will be "streamed",
which means it will be made available via the requests.Response object
rather than consumed and set on the DetailedResponse object.
To access the streamed response, simply retrieve the requests.Response
object by calling DetailedResponse.get_result(), then use the "iter_content"
method on the returned requests.Response instance.
=> feat(BaseService): support stream=True in BaseService.send()

setup.py
This PR eliminates the logic in `setup.py` that converted `README.md` to "restructured text" format.  This logic depended on `pandoc` and `pypandoc` but these packages were not identified as dependencies in the "requirements" files.  This could result in scary error messages for users.  And this seems completely unnecessary since PyPI handles markdown format just fine.
=> chore: drop pandoc conversion of README in setup.py

ibm_cloud_sdk_core/authenticators/iam_authenticator.py, ibm_cloud_sdk_core/get_authenticator.py, ibm_cloud_sdk_core/iam_token_manager.py, resources/ibm-credentials.env, test/test_iam_authenticator.py, test/test_iam_token_manager.py, test/test_utils.py
The IAM /identity/token (get token) operation supports an optional "scope" form parameter which can be used to obtain an IAM access token having a limited set of scopes in this it can be used.
This commit adds support for the "Scope" field within the IamTokenManager class. If set, the value of this field is sent as the "scope" form param in the "get token" request body when obtaining an access token.
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/2167
=> feat(IAM Authenticator): add support for optional 'scope' property

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/2290
Using gzip instead of zlib will avoid an issue when compressing and decompressing gzip file data.
=> fix: replace zlib with gzip for gzip compression

.gitignore, ibm_cloud_sdk_core/utils.py, test/test_utils.py
Fixes arf/planning-sdk-squad#2313
This commit adds new tests for the datetime_to_string and
string_to_datetime functions to ensure that each of the required
date-time formats are supported.  These new tests are aligned
with similar tests in the Java and Go cores.
Edit: I originally included a change to datetime_to_string() to use only milliseconds precision when marshalling a datetime value, but it turns out that the python versions we build with on Travis do not support the use of the "timespec" parameter on the datetime.isoformat() function.   So, I'll leave datetime_to_string() alone for now and it will continue to produce strings with microsecond precision, which leaves us no worse off than we were before.   But the addition of the new tests should provide us with some confidence that …
=> test: add tests re: date-time marshalling/unmarshalling

requirements.txt
The `requests` library added dependencies that use LGPL in version 2.16. To avoid these we can restrict the library to versions before 2.16
=> fix: restrict requests version to newer version to avoid vulnerability

requirements-dev.txt, requirements.txt
PyJWT version >=2.0.0 had a recent breaking change, this restricts the version until we update our code to use the new change. This also adds a max version to the other requirements
=> chore: update PyJWT version to <2.0.0 and restrict other req versions

requirements-dev.txt
Increase the minimum versions for some requirements and cause a minor version release for the requirements changes.
=> fix: bump minimum requirement versions

ibm_cloud_sdk_core/jwt_token_manager.py, requirements.txt, test/test_base_service.py, test/test_cp4d_authenticator.py, test/test_cp4d_token_manager.py, test/test_iam_authenticator.py, test/test_iam_token_manager.py
This change includes updates to the jwt.decode call from by updating the verify options from https://github.com/IBM/python-sdk-core/pull/89 and specifying the algorithm in the decode to satisfy new changes in version 2.0.0 of pyjwt.
=> fix: update pyjwt parameters to satisfy 2.x changes

setup.py
The setup.py requirements should match the requirements.txt. Using the same method from the python sdk template, this change loads setup the reqs from the requirements.txt file
=> fix: update setup.py requirements to match requirements.txt

MANIFEST.in
requirements.txt needs to be included in the MANIFEST.in file to be included in setup.py
=> fix: include requirements.txt in MANIFEST.in for setup.py reference

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
Closes #83
Updated from https://github.com/IBM/python-sdk-core/pull/84
=> feat(BaseService): Use a `requests.Session` object to configure retries and other configuration

Authentication.md, Makefile, ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/utils.py, test/test_utils.py
While attempting to read configuration properties from
the config file specified via ${IBM_CREDENTIALS_FILE}, the
read_external_sources() function should silently ignore
an error if the file doesn't exist, and then proceed
to the next step of the config algorithm.
This was not working correctly, but this commit fixes that.
Also fixes: #60
=> fix: silently ignore missing configuration file

.gitignore, ibm_cloud_sdk_core/iam_token_manager.py, test/test_iam_authenticator.py, test/test_iam_token_manager.py
The IAM Authenticator now exposes the `refresh_token` variable which is set when a `get_token()` request is made and a refresh token is returned.
=> feat: expose refresh token in iam authenticator

ibm_cloud_sdk_core/__init__.py, ibm_cloud_sdk_core/utils.py, test/test_utils.py
This PR adds a small utility method to extract the value of a query parameter from a URL string. This will be used in the pagination support for Python.
=> Add get_query_param utility method to support pagination

ibm_cloud_sdk_core/__init__.py, ibm_cloud_sdk_core/utils.py, test/test_utils.py
Adds two util functions to convert a list of DateTime to a list of str and vice versa. This is used for a new fix in the Python generator for formatting mock data values for generated unit tests.
=> feat: add datetime to string utils for lists

.secrets.baseline, Authentication.md, ibm_cloud_sdk_core/authenticators/cp4d_authenticator.py, ibm_cloud_sdk_core/cp4d_token_manager.py, ibm_cloud_sdk_core/get_authenticator.py, resources/ibm-credentials-cp4dtest.env.example, test/test_base_service.py, test/test_cp4d_authenticator.py, test/test_cp4d_token_manager.py, test_integration/test_cp4d_authenticator_integration.py
Adds support for API key and password support in the CP4D authenticator and updated authorization URL.
=> feat: support api key use case for CP4D authenticator

test/test_base_service.py, test/test_cp4d_authenticator.py, test/test_iam_authenticator.py
This PR just adds a few tests to verify that we can explicitly set the Host header in various ways such that it shows up in the resulting http request.
=> test: add tests that explicitly set the Host request header

.pylintrc, ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
This PR introduces a minor change/improvement: removal of some reserved keys from the `kwargs` of the base services' send function.
=> fix: remove reserved keywords from kwargs before passing it to requests

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
This PR adds encoding to the serialized JSON payload. We are already doing this if the payload is passed as a string.
In the generated SDKs, for example in the [Platform Services/Case Management](https://github.com/IBM/platform-services-python-sdk/blob/main/ibm_platform_services/case_management_v1.py#L217), we serialize the `data` dictionary and pass it to the `prepare_request` function as a string, therefore I think it's safe to add encoding here.
=> fix: encode serialized JSON string as UTF-8

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
This commit changes the default value of the retry_interval
parameter (in the BaseService.enable_retries method) from 0.1
to 1.0.   This will result in default retry intervals
of 1, 2, 4, 8, ... seconds instead of 0.1, 0.2, 0.4, 0.8, ... seconds.
This change will align the python core retry support with Go.
Also added some detailed info in the docstring for the method as well.
=> fix(retries): change default retry_interval to 1 second (was 0.1)

ibm_cloud_sdk_core/token_managers/container_token_manager.py, ibm_cloud_sdk_core/token_managers/iam_request_based_token_manager.py, ibm_cloud_sdk_core/utils.py, test/test_base_service.py, test/test_container_token_manager.py, test/test_detailed_response.py, test/test_iam_authenticator.py
This PR fixes an issue which happens when the user creates more than one IAM based authenticator in the same service/project/file. The cause of this issue is the `request_payload` class variable, because it should be an instance variable.
Tests have been added, fixed and improved.
Closes #123 
Update: there are also some unicode string and utf-8 encoding related changes in this PR to make the code compatible with the latest pylint release.
=> fix: multiple IAM based authenticator overrides

.pylintrc, .secrets.baseline, .travis.yml
This PR bumps us up to node v14 to accommodate the new semantic-release v18
For some reason, my initial change to bump node to v14 resulted in some additional lint warnings related to the use f-strings and failed the build.  I added another change to disable that lint check as a bit of research revealed that it's a dubious check to perform anyhow :)
=> chore(build): use node 14 for new semantic-release

.secrets.baseline, Authentication.md, ibm_cloud_sdk_core/__init__.py, ibm_cloud_sdk_core/authenticators/__init__.py, ibm_cloud_sdk_core/authenticators/authenticator.py, ibm_cloud_sdk_core/authenticators/vpc_instance_authenticator.py, ibm_cloud_sdk_core/get_authenticator.py, ibm_cloud_sdk_core/token_managers/vpc_instance_token_manager.py, resources/ibm-credentials-vpc.env, test/test_utils.py, test/test_vpc_instance_authenticator.py, test/test_vpc_instance_token_manager.py
This PR introduces the VPCInstanceAuthenticator.
This authenticator implements the authentication flow
within a VPC-managed compute resource that is configured to
use the compute resource identity feature.
This involves the use of the compute resource's local
VPC Instance Metadata Service API to retrieve an instance identity
token, and then exchange that token for an IAM access token.
The IAM access token is then used to authenticate outbound REST
API requests by adding an Authorization containing the access token.
=> feat(VPCInstanceAuthenticator): add support for new VPC authentication flow

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py, test/test_utils.py
This commit modifies the BaseService.set_service_url()
function so that it removes any trailing slashes.
Previously, a service URL containing a trailing slash
(e.g. "https://myserver.com/api/v1/") would result in a
request URL that contains two slashes between the service URL
and the operation path (e.g. "https://myserver.com/api/v1//myoperationpath"),
and some server implementations might fail to process such
a request properly.
With the changes in this commit, a request URL of
"https://myserver.com/api/v1/myoperationpath" will be used instead.
=> fix: strip trailing slashes in BaseService.set_service_url

.travis.yml, Makefile
This PR fixes a recent pylint problem seen with python 3.7.1 (the default version used by the travis xenial build image) by upgrading the build up to the bionic image where python 3.7.6 is used instead.
I also took this opportunity to remove the use of tox in the travis build since it's really not needed.  Instead, we just run the "make ci" command in each of the travis build jobs (one job per python version... 3.6 - 3.9).
=> build: use bionic dist in travis

requirements.txt
This PR bumps up our requests dependency to 2.26.0, and explicitly adds a dependency on urllib3 (>= 1.26.0) due to the retry-related code in the python core.
=> build: bump requests and urllib3 deps

ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/token_managers/container_token_manager.py, ibm_cloud_sdk_core/token_managers/vpc_instance_token_manager.py
Hi!
We've been using this package for around a year now and have really enjoyed how simple it makes submitting queries to the Watson API.
However, we'd like to be able to control the level of logging produced by the library. At present this is difficult since all of the modules what use logging do it via the root logger (so it's impossible to pin-point just what we are turning off).
In this MR I have used the module name for each module that employs logging. This means that clients using the package can now selecting turn logging on or off for this package. This is the behaviour that is implemented in many popular Python packages like `requests`.
Thanks, Andrew.
=> feat: use module names for loggers

ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/utils.py, test/test_base_service.py
This PR introduces a custom HTTP adapter that wraps the original one
and adds SSL context, that sets the minimum TLS version required to v1.2.
=> chore: set minimum TLS version to v1.2

ibm_cloud_sdk_core/authenticators/authenticator.py, ibm_cloud_sdk_core/base_service.py, test/test_api_exception.py, test/test_base_service.py, test/test_detailed_response.py
Fixes: arf/planning-sdk-squad#3250
This PR avoids a warning being logged when the 'headers' key is removed from kwargs by the BaseService.send() method.
=> fix: avoid warning when custom headers are used

.travis.yml
This commit fixes the version of the `setuptools` package for Python 3.7
and 3.8 builds to address build issues.
=> build: used fixed version of setuptools for Python 3.7 and 3.8

ibm_cloud_sdk_core/authenticators/cp4d_authenticator.py, ibm_cloud_sdk_core/token_managers/cp4d_token_manager.py
These modifications allow the user to have a self-signed certificate in the SSL verification process when authenticating to an STT instance on CP4D.
The `verify` attribute is used by the [requests python module](https://pypi.org/project/requests/) to indicate the path to a custom CA Bundle ([resquests documentation](https://requests.readthedocs.io/en/latest/api/?highlight=verify)).
With these changes, it wont be necessary to disable ssl verification anymore when using a self-signed certificate with STT on CP4D.
=> feat(CP4D Authentication): add ssl verification for self-signed certificates

ibm_cloud_sdk_core/detailed_response.py
Fixes: #145
This PR updates the docstrings and type hints within DetailedResponse to correctly
convey the various possible types of values returned by `get_result()`.
=> docs: update docstring/type hints for DetailedResponse class

Authentication.md, ibm_cloud_sdk_core/token_managers/container_token_manager.py, test/test_container_token_manager.py
This commit adds support for a second default CR token filename. If the user doesn't specify a CR token filename, the authenticator will first try '/var/run/secrets/tokens/vault-token', and then '/var/run/secrets/tokens/sa-token' in that order.
=> fix(ContainerAuthenticator): add sa-token as default CR token filename

ibm_cloud_sdk_core/base_service.py, test/test_base_service.py
When we introduced the new `GzipStream` utility class which
handles the on-the-fly compression of the file like object.
We also started using it for in-memory objects, like bytes,
but it has introduced a minor incompatibility with the existing SDKs.
This commit contains the fix for that. From now the new utility class
will be used only for file-like objects and the rest of the types will
be handled as before (compressing in memory).
=> fix: use on-the-fly compression only for file objects

.secrets.baseline, Authentication.md, Makefile, ibm_cloud_sdk_core/__init__.py, ibm_cloud_sdk_core/authenticators/__init__.py, ibm_cloud_sdk_core/authenticators/authenticator.py, ibm_cloud_sdk_core/authenticators/basic_authenticator.py, ibm_cloud_sdk_core/authenticators/bearer_token_authenticator.py, ibm_cloud_sdk_core/authenticators/cp4d_authenticator.py, ibm_cloud_sdk_core/authenticators/iam_request_based_authenticator.py, ibm_cloud_sdk_core/authenticators/mcsp_authenticator.py, ibm_cloud_sdk_core/authenticators/vpc_instance_authenticator.py, ibm_cloud_sdk_core/get_authenticator.py, ibm_cloud_sdk_core/token_managers/mcsp_token_manager.py, resources/ibm-credentials-mcsp.env, test/test_mcsp_authenticator.py, test/test_mcsp_token_manager.py, test/test_utils.py, test_integration/test_mcsp_authenticator_integration.py
This commit introduces the new MCSPAuthenticator that can be used to exchange an apikey for an MCSP access token using the Multi-Cloud Saas Platform authentication token server's 'POST /siusermgr/api/1.0/apikeys/token' operation.
=> feat(MCSPAuthenticator): add new authenticator for Multi-Cloud Saas Platform

ibm_cloud_sdk_core/api_exception.py, ibm_cloud_sdk_core/detailed_response.py, test/test_api_exception.py, test/test_base_service.py, test/test_container_token_manager.py
This commit fixes a small inconsistency in the naming
of the HTTP status code attributes between the successful
and the error responses.
=> fix: more consistent naming of HTTP status code related attributes

.secrets.baseline, ibm_cloud_sdk_core/token_managers/iam_request_based_token_manager.py, ibm_cloud_sdk_core/token_managers/vpc_instance_token_manager.py, test/test_container_token_manager.py, test/test_iam_token_manager.py, test/test_vpc_instance_token_manager.py
This commit changes the IAM, Container and VPC Instance authenticators slightly so that an IAM access token will be viewed as "expired" when the current time is within 10 seconds of the official expiration time. IOW, we'll expire the access token 10 secs earlier than the IAM server-computed expiration time.
We're doing this to avoid a scenario where
an IBM Cloud service receives a request along
with an "almost expired" access token and then uses that token to perform downstream requests in a
somewhat longer-running transaction and then the
access token expires while that transaction is
still active.
=> fix: adjust IAM token expiration time

ibm_cloud_sdk_core/base_service.py
This commit simply modifies the docstring comments related to the `headers` and `params` arguments to the `BaseService.prepare_request()` function in order to clarify that any entries in either of the two dictionary arguments will simply be ignored if they have a value of None.
=> refactor(BaseService): improve prepare_request() docstring

ibm_cloud_sdk_core/utils.py, requirements.txt
Version `2.23.3` of the `requests` package broke our custom `SSLHTTPAdapter`. This commit defines the maximum version of that package, to make sure it will continue working without an issue. Note that, this is a short term solution only. For more details see this issue: https://github.com/psf/requests/issues/6730
=> fix: specify the maximum version of `requests` to avoid regression

.travis.yml, test/test_api_exception.py, test/test_jwt_token_manager.py, test/test_token_manager.py
This commit makes some minor changes to a few testcases:
1. test_api_exception.py: add tests for some requests.Response operations
2. test_token_manager.py/test_jwt_token_manager.py: modified the abstract base class checks to work in Python 3.12 by matching only part of the error message that appears in the exception
3. I also added python 3.12 to the travis build definition since I found and fixed a couple of unit test errors when using python 3.12
=> test: minor updates to a few testcases

ibm_cloud_sdk_core/http_adapter.py, test/test_http_adapter.py
Follow up PR of https://github.com/IBM/python-sdk-core/pull/196. Turned out in some cases - especially in containers - the certificate verification is still failing due to the missing certs. It's because the location of those files really depend on the system and the OpenSSL configuration.
This PR adds a workaround for this problem, by loading the default certs from the location that the `certifi` package reports. The `requests` package uses the same logic, so it should cause no issues.
=> fix: improve the detection and loading of default certificates

test/test_http_adapter.py
A recently introduced unit test uses the `ConnectionError` class from the standard library
to check the type of a returned exception, but that's not correct because the actual
exception that can be thrown there is the `requests.exceptions.ConnectionError`.
This confusion made the tests fail sometimes.
=> test: use the correct `ConnectionError` class in the tests

setup.py
The `test` command and related function were deprecated for 5 years
and it seems the time has come: setuptools maintainers removed it
yesterday and that move has broken a bunch of Python packages
including this. After looking into several documentations and our source
code, I think the right thing to do - instead of making a workaround - is
**completely removing** it from our `setup.py` file as it hasn't been used for
a long time - correct me if I am wrong here and missed something!!
Some details:
- Issue in the `setuptools` repo: https://github.com/pypa/setuptools/issues/4519
- The commit that introduced this: https://github.com/pypa/setuptools/commit/4c0b9f3ee6ee47c597572655567f215c08c90137
- Release note: https://setuptools.pypa.io/en/stable/history.html#deprecations-and-removals
> The …
=> fix: remove `test` command and related code from `setup.py`

ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/logger.py, test/test_base_service.py, test/test_http_adapter.py, test/test_logger.py, test/utils/http_utils.py, test/utils/logger_utils.py
This PR improves the debug logging logic in the core,
so that secrets are not shown in the debug logs anymore.
FYI: this PR targets the `debug-logging` feature branch.
=> feat: redact secrets in debug logging

.secrets.baseline, Authentication.md, README.md, ibm_cloud_sdk_core/__init__.py, ibm_cloud_sdk_core/authenticators/__init__.py, ibm_cloud_sdk_core/authenticators/authenticator.py, ibm_cloud_sdk_core/authenticators/container_authenticator.py, ibm_cloud_sdk_core/authenticators/iam_assume_authenticator.py, ibm_cloud_sdk_core/base_service.py, ibm_cloud_sdk_core/get_authenticator.py, ibm_cloud_sdk_core/token_managers/container_token_manager.py, ibm_cloud_sdk_core/token_managers/iam_assume_token_manager.py, ibm_cloud_sdk_core/token_managers/iam_request_based_token_manager.py, resources/ibm-credentials-iam-assume.env, test/test_authenticator.py, test/test_container_authenticator.py, test/test_container_token_manager.py, test/test_iam_assume_authenticator.py, test/test_iam_assume_token_manager.py, test/test_utils.py, test_integration/test_iam_assume_authenticator_integration.py
This commit introduces the new `IAMAssumeAuthenticator` which will fetch an IAM access token using the IAM `get_token` operation's "assume" grant type. The resulting access token allows the application to assume the identity of a trusted profile, similar to the "sudo" feature of Linux.
=> feat(IamAssumeAuthenticator): introduce a new authenticator

Authentication.md, ibm_cloud_sdk_core/token_managers/container_token_manager.py
This pull request extends the existing ContainerAuthenticator to be aware of the hard-coded compute resource token path used by Code Engine. This allows a seamless usage of that authenticator and a move of workload between IKS/ROKS/Code Engine without changing a single line of code.
Documentation is adjusted to mention Code Engine in the context of the ContainerAuthenticator.
=> feat(ContainerAuthenticator): enhance ContainerAuthenticator to support Code Engine workload
